
# Making copies of the app

The app is hosted on GitHub pages, and will work as long as it does not exceed their permitted bandwidth. Because processing takes place in the browser, rather than on a server, this is very unlikely happen.

However, it's probably best to make your own copies of the app. Here are a couple of ways to do this.    

## 1. Running locally as a "Progressive Web App"

This is by far the neatest and most user-friendly way to make a local copy of the app. Your browser saves the app as a web page. However, bear in mind, that because an online service is used for part-of-speech tagging, your computer will need to be connected to the internet for it to work.

Below are instructions on how to create "Progressive Web Apps" in the most widely-used browsers. If you use a different browser, a quick internet search, or query to a large language model, will provide you with instructions.

**Chrome (Windows/Mac/Linux)**

- Visit mimolanguageanalysis.uk
- Click the menu icon (⋮) in the top-right corner
- Select "Install MiMo Language Analysis..." or "Save and Share" → "Install page as app"
- Click Install in the popup

The app will open in a new window and add an icon to your desktop/applications

**Edge (Windows/Mac)**

- Visit mimolanguageanalysis.uk
- Click the menu icon (⋯) in the top-right corner
- Select "Apps" → "Install this site as an app"
- Click Install in the popup

The app will appear in your Start menu (Windows) or Applications folder (Mac)

**Safari (Mac/iOS)**

Safari doesn't support PWA installation the same way, but you can create a home screen shortcut:

*On Mac:*

- Visit mimolanguageanalysis.uk
- Click File → "Add to Dock"

The site will appear as an app in your Dock

*On iPhone/iPad:*

- Visit mimolanguageanalysis.uk in Safari
- Tap the Share button (square with arrow)
- Scroll down and tap "Add to Home Screen"
- Tap Add
- The app icon will appear on your home screen

**Firefox**

Firefox has limited PWA support:

*Windows*: No PWA installation available—just bookmark the site
*Android*: Menu (⋮) → "Install"


## 2. Running the R code locally

If you are familiar with the R environment, you can download the app.R files from github, and just run them.

The URL for the the MiMo app is:

[https://github.com/nickriches/MiMoShinyLive](https://github.com/nickriches/MiMoShinyLive)

and the URL for the Norms is:

[https://github.com/nickriches/MiMoShinyLiveNorms](https://github.com/nickriches/MiMoShinyLiveNorms)

In order for the apps to run, you will need to install a variety of packages.
The following code automatically does this:

1. For the MiMo app

```
requiredpackages <- c('shiny', 'DT', 'dplyr',
'stringr', 'udpipe' 'textcat', 'zoo',
'koRpus', 'koRpus.lang.en', 'colourpicker')

install_load <- function(packages){
     for (p in packages) {
          if (p %in% rownames(installed.packages())) {
               library(p, character.only=TRUE)
          } else {
               install.packages(p)
               library(p,character.only = TRUE)
          }
     }
}

install_load(requiredpackages)

```

1. For the MiMo norms

```
requiredpackages <- c('shiny', 'ggplot2', 'dplyr', 'zoo')

install_load <- function(packages){
     for (p in packages) {
          if (p %in% rownames(installed.packages())) {
               library(p, character.only=TRUE)
          } else {
               install.packages(p)
               library(p,character.only = TRUE)
          }
     }
}

install_load(requiredpackages)

```

Note that if you do this you will still need to have your computer connected to the internet this is because (a) the MiMo app needs to download the Universal Dependency grammar (b) the MiMo app reads the normative data from a specially made github page.

It should also be noted that some of the hyperlinks at the top of the page will not work because they point to existing web locations.
